import streamlit as st
import pandas as pd

# ==========================================
# 1. PAGE SETUP & CONFIGURATION
# ==========================================
st.set_page_config(page_title="True Free Cash Engine", page_icon="💰", layout="wide")

st.title("💼 True Free Cash & EOY Tax Forecasting Engine")
st.write("Strip away business overhead and accurate tax liabilities to see exactly what you can withdraw right now.")
st.write("---")

# Define the Indian Financial Year sequence (April to March)
FY_MONTHS = [
    "April", "May", "June", "July", "August", "September", 
    "October", "November", "December", "January", "February", "March"
]

# ==========================================
# 2. BASELINE DATA CONFIGURATION
# ==========================================
# Setting up standard default revenue and overhead frameworks
baseline_data = {
    "Month": FY_MONTHS,
    "Estimated_Revenue": [500000] * 12,
    "Fixed_Overhead": [150000] * 12,
}
df_base = pd.DataFrame(baseline_data)

# ==========================================
# 3. INTERACTIVE CONTROLS (SIDEBAR)
# ==========================================
st.sidebar.header("🛠️ Engine Controls")

# Control 1: Choose the starting configuration month
current_month = st.sidebar.selectbox(
    "Select the Current Active Month:", 
    options=FY_MONTHS, 
    index=2 # Defaults to June
)
current_month_idx = FY_MONTHS.index(current_month)

st.sidebar.write("---")
st.sidebar.subheader("🔮 Variable Overhead Inputs")
st.sidebar.caption("Tweak operational constraints for your active month and remaining future cycles:")

# Capture the user input for the CURRENT month's changeable overhead
st.sidebar.markdown(f"**Current Month ({current_month})**")
current_changeable_overhead = st.sidebar.number_input(
    f"Active Overhead for {current_month}:",
    min_value=0,
    value=int(df_base.loc[current_month_idx, "Fixed_Overhead"]),
    step=5000,
    key="current_oh"
)

# ==========================================
# 4. CORE ENGINE LOGIC & CALCULATIONS
# ==========================================
final_monthly_records = []

# Build the dynamic 12-month fiscal spreadsheet model
for idx, row in df_base.iterrows():
    month_name = row["Month"]
    revenue = row["Estimated_Revenue"]
    
    if idx < current_month_idx:
        # PAST MONTHS: Closed History
        status = "Past (Closed)"
        overhead = row["Fixed_Overhead"]
    elif idx == current_month_idx:
        # CURRENT MONTH: Driven dynamically by our primary lever variable
        status = "Present (Active)"
        overhead = current_changeable_overhead
    else:
        # FUTURE MONTHS: Auto-populated by current month's variable, but editable individually
        status = "Future (Projected)"
        overhead = st.sidebar.number_input(
            f"Projected Overhead ({month_name}):",
            min_value=0,
            value=int(current_changeable_overhead),
            step=5000,
            key=f"oh_{month_name}"
        )
        
    net_profit = max(0, revenue - overhead)
    # Estimated Corporate Tax (Assumed flat baseline rate of 25% on business profit margins)
    calculated_tax = net_profit * 0.25
    # Estimated TDS tracking (Assumed standard 10% source deduction on inbound gross revenue streams)
    calculated_tds = revenue * 0.10
    
    final_monthly_records.append({
        "Month": month_name,
        "Status": status,
        "Revenue": revenue,
        "Overhead": overhead,
        "Net Profit": net_profit,
        "Tax Liability": calculated_tax,
        "TDS": calculated_tds
    })

df_engine = pd.DataFrame(final_monthly_records)

# ==========================================
# 5. LIQUIDITY INPUTS & WATERFALL MATH
# ==========================================
col_input1, col_input2, col_input3 = st.columns(3)

with col_input1:
    bank_balance = st.number_input(
        "💵 Current Bank Balance (₹):", 
        min_value=0, 
        value=1000000, 
        step=25000
    )

with col_input2:
    tax_paid_so_far = st.number_input(
        "🏛️ Actual Tax Settled Up to Date (₹):",
        min_value=0,
        value=0,
        step=5000,
        help="Input your real-world historical settlements (Advance Tax, TDS credits used, or Q1 payouts)."
    )

with col_input3:
    st.caption("ℹ️ **Engine Rule Framework**")
    st.info(f"The engine assumes you have settled all taxes prior to **{current_month}** via the input amount. It will now isolate and reserve fresh taxes generated by **{current_month}**.")

st.write("---")

# Core Liquidity Math execution
current_month_overhead_commitment = df_engine.loc[current_month_idx, "Overhead"]
current_month_tax_liability = df_engine.loc[current_month_idx, "Tax Liability"]

# Ultimate Authorization Equation: Balance minus current commitments and dynamic month tax
freely_withdrawable_cash = bank_balance - current_month_overhead_commitment - current_month_tax_liability

# ==========================================
# 6. VISUAL METRICS DISPLAY
# ==========================================
st.subheader("🏁 Safe Withdrawal Matrix")

if freely_withdrawable_cash >= 0:
    st.success(f"### Freely Withdrawable Cash: **₹{freely_withdrawable_cash:,.2f}**")
else:
    st.error(f"### Shortfall Warning! Negative Liquidity Balance: **₹{freely_withdrawable_cash:,.2f}** (Operational Capital Injection Required)")

# Explanatory breakdown expander
with st.expander("🔍 Operational Breakdown"):
    st.write(f"**Starting Bank Balance Raw Liquidity:** ₹{bank_balance:,.2f}")
    st.write(f"⚠️ *Minus* Active Monthly Overhead Budget Allocation ({current_month}): -₹{current_month_overhead_commitment:,.2f}")
    st.write(f"⚠️ *Minus* Live Predicted Tax Liability Generated for Current Month Revenue: -₹{current_month_tax_liability:,.2f}")
    st.write("---")
    st.write(f"**Net Discovered Spendable Capital:** ₹{freely_withdrawable_cash:,.2f}")

st.write("---")

# ==========================================
# 7. END OF YEAR FORECASTING BLOCKS
# ==========================================
st.subheader("📊 Full-Year Fiscal Projections (EOY Estimates)")

eoy_revenue = df_engine["Revenue"].sum()
eoy_overhead = df_engine["Overhead"].sum()
eoy_calculated_tax = df_engine["Tax Liability"].sum()
eoy_tds = df_engine["TDS"].sum()

# Adjust corporate calculations to account for real-world tax payments entered
net_final_tax_payout_due = max(0, eoy_calculated_tax - tax_paid_so_far)

col_m1, col_m2, col_m3, col_m4 = st.columns(4)
with col_m1:
    st.metric(label="Total Projected Revenue", value=f"₹{eoy_revenue:,.2f}")
with col_m2:
    st.metric(label="Est. Corporate Tax (Total Yr)", value=f"₹{eoy_calculated_tax:,.2f}")
with col_m3:
    st.metric(label="Estimated TDS Accrued", value=f"₹{eoy_tds:,.2f}")
with col_m4:
    st.metric(label="Net EOY Balance Due to Gov", value=f"₹{net_final_tax_payout_due:,.2f}", delta=f"-₹{tax_paid_so_far} Paid", delta_color="inverse")

# Render underlying operational database grid
st.write("### 📋 Underlying 12-Month Financial Spread Matrix")
st.dataframe(df_engine, use_container_width=True)
